Squashed 'lib/ArduinoJson/' changes from f2ef338c..729bf0af
729bf0af Made JsonBuffer destructor protected
2ea7ea15 Set version to 5.11.1
2772e660 Fixed warning "this statement may fall through" (issue #539)
d41f7a81 Fixed too many decimals places in float serialization (issue #543)
abfd3997 Fixed "constant exceeds range of float [-Woverflow]" (issue #544)
788c9be0 Removed dependency on `PGM_P` as Particle 0.6.2 doesn't define it (issue #546)
c3d7a79a Travis: Removed Arduino DUE on platformio (fatal error: Ethernet.h: No such file or directory)
17823482 Added Charles Walker to the list of donators
edfe5c66 Set version to 5.11.0
2b949231 Added Charles Haynes to the list of donators
5da41edf Removed implementation of `JsonBufferAllocated::delete`.
476e5aaa Added `DynamicJsonBuffer::clear()`
789fa507 Added `StaticJsonBuffer::clear()`
508f9363 Made `JsonBuffer` non-copyable (PR #524 by @luisrayas3)
e9d88dda Set version to 5.10.1
ecceb71a AppVeyor: Added Visual Studio 2017 and restored MinGW
bff77abe Fixed reading "true" as a float (issue #516)
98413089 Added Google to the list of donators
a2446f6c Fixed compilation in IAR Embedded Workbench (issue #515)
c9550492 Fixed IntelliSense errors in Visual Micro (issue #483)
574c00c0 Added links to the ArduinoJson assistant (issue #513)
7415f206 Reduced code size
f76017a0 Set version to 5.10.0
cda05aec Removed configurable number of decimal places (issues #288, #427 and #506)
639286f8 Travis: Removed retired images
cc66618e Fixed error `forming reference to reference` (issue #495)
9efc0ec4 Travis: Added GCC 6
34674fc2 Fixed error `IsBaseOf is not a member of ArduinoJson::TypeTraits` (issue #495)
01c31660 Moved testimonials to https://bblanchon.github.io/ArduinoJson/
bf2e3d56 Updated the list of supported hardware (issue #491)
4e9f0b2e Set version to 5.9.0
223f1471 Now compatible with Particle 0.6.1 (issue #294 and PR #461 by @foodbag)
f7ae91b8 Removed unused stuffs
445dff49 ctest --output-on-failure
9afa05e2 Removed `Print` class and converted `printTo()` to a template method (issue #276)
c3e1677b Fixed warnings `floating constant exceeds range of float`and `floating constant truncated to zero` (issue #483)
024976cd Renamed folder `include/` to `src/` (issue #461)
df541a2a Changed unit testing framework from Google Test to Catch

git-subtree-dir: lib/ArduinoJson
git-subtree-split: 729bf0afd284b3302255c62631e9c00719987dcf